---
# tasks file for x2go-server
- name: Add x2go ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:x2go/stable
  become: true

- name: x2go server packages
  ansible.builtin.apt:
    name: "{{ x2go_packages }}"
    state: present
  become: true
