---
# tasks file for x2go-server
- name: Add x2go ppa repository
  apt_repository: 
    repo: ppa:x2go/stable
  become: yes

- name: x2go server packages
  apt: 
    name: "{{ x2go_packages }}" 
    state: present
  become: yes
